# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 23:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_terreno_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terreno',
            name='descricao',
            field=models.CharField(max_length=100, verbose_name='descrição do terreno'),
        ),
    ]
