# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20171105_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='edification_type',
            field=models.CharField(choices=[('Comercial', 'Comercial'), ('Residencial', 'Residencial'), ('Industrial', 'Industrial'), ('Institucional', 'Institucional')], default='Comercial', max_length=50, verbose_name='tipo de edificação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='terreno',
            name='number_pav',
            field=models.IntegerField(default=3, verbose_name='número de pavimentações'),
            preserve_default=False,
        ),
    ]
