# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_setor'),
    ]

    operations = [
        migrations.AddField(
            model_name='terreno',
            name='setor',
            field=models.CharField(default='Setor 04', max_length=50, verbose_name='setor'),
            preserve_default=False,
        ),
    ]
