# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_terreno_setor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodUrbanismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=50)),
                ('uso_permitido', models.CharField(max_length=50)),
                ('area_minima', models.CharField(max_length=50)),
                ('frente_minima', models.CharField(max_length=50)),
                ('taxa_ocupacao', models.CharField(max_length=50)),
                ('altura_maxima', models.CharField(max_length=50)),
                ('afast_frente', models.CharField(max_length=50)),
                ('afast_lateral', models.CharField(max_length=50)),
                ('afast_fundos', models.CharField(max_length=50)),
            ],
        ),
    ]
