# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 01:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_zona_extenso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonaCreator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('descriptio', models.CharField(max_length=254)),
                ('timestamp', models.CharField(max_length=24)),
                ('begin', models.CharField(max_length=24)),
                ('end', models.CharField(max_length=24)),
                ('altitudemo', models.CharField(max_length=254)),
                ('tessellate', models.IntegerField()),
                ('extrude', models.IntegerField()),
                ('visibility', models.IntegerField()),
                ('draworder', models.IntegerField()),
                ('icon', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
