# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-03 01:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_zonacreator'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZonaCreator',
        ),
    ]
